### ISSUE TITLE
🐛[BUG] wrong tslib version used in Jest

### ISSUE THREAD

**Issue by mboettcher** [ant-design/ant-design-charts#1276]
### 🐛 Bug description 
Jest tests fail with `TypeError: tslib_1.__spreadArray is not a function`. It works fine in the browser. 

```
 Test suite failed to run

    TypeError: tslib_1.__spreadArray is not a function

    > 1 | import { Line, LineConfig } from '@ant-design/charts';
        | ^

      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/command-contributions/command-contribution.ts:32:18)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/command-contributions/module.ts:15:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/command-contributions/components/index.tsx:3:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/command-contributions/index.tsx:28:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/xflow-main/components/index.tsx:17:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/xflow-main/index.tsx:1:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow-core/src/index.tsx:15:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow/src/core/index.ts:1:1)
      at Object.<anonymous> (../../node_modules/@antv/xflow/src/index.tsx:1:1)
      at Object.<anonymous> (../../node_modules/@ant-design/flowchart/lib/index.js:21:15)
      at Object.<anonymous> (../../node_modules/@ant-design/charts/lib/index.js:19:14)
      at Object.<anonymous> (.../ProgressChartCard.tsx:1:1)
      at Object.<anonymous> (.../ProgressChartCard.test.tsx:4:1)
```

In general, tslib > 2.1.x is installed. However, it seems that `xflow-core` requires `rxjs` which requires the dependency ""tslib": "^1.9.0"".  yarn created a `node_modules` folder in `xflow-core` which contains a tslib version below 2. Not sure if that is helpful.

I have no idea why it fails in Jest but works fine with webpack / in the browser.

### 🏞 Desired outcome 
Jest runs without errors.

### © Version information

- ant-design-charts version: 1.3.6
- Browser environment: Jest 27.5.1
- Development environment mac OS

### 🚑 Other information

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/576

**Comment by mboettcher** [comment]
Adding tslib doesn't solve the issue. It's a dependency hell.

**Comment by RiteshMakan** [comment]
@mboettcher Did you find a solution for this? 

I tried with both 
`npm install tslib --save` and with `npm install tslib@latest --save`

I still

**Comment by phugodness** [comment]
i'm in pain with this issue :/
