### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module using nextjs typescript 🐛[BUG]

### ISSUE THREAD

**Issue by aseph8083** [ant-design/ant-design-charts#1736]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

i'm using nextjs when i'm running show error 

error - Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Projek\dashboard\node_modules\d3-interpolate\src\index.js from D:\Projek\dashboard\node_modules\@antv\g-base\lib\animate\timeline.js not supported.
Instead change the require of index.js in D:\Projek\dashboard\node_modules\@antv\g-base\lib\animate\timeline.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g-base\lib\animate\timeline.js:5:24)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g-base\lib\abstract\canvas.js:7:18)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g-base\lib\index.js:17:16)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\dependents.js:6:16)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\util\scale.js:7:20)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\util\axis.js:6:15)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\facet\facet.js:7:14)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\facet\index.js:5:15)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\chart\view.js:8:15)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\chart\chart.js:8:38)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\chart\index.js:7:15)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\core.js:10:15)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2\lib\index.js:6:14)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@antv\g2plot\lib\index.js:7:31)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@ant-design\plots\lib\components\area\index.js:41:16)
    at Object.<anonymous> (D:\Projek\dashboard\node_modules\@ant-design\plots\lib\index.js:21:30)
    at @ant-design/plots (D:\Projek\dashboard\.next\server\pages\index.js:351:18)
    at __webpack_require__ (D:\Projek\dashboard\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./component/neraca/chart_data.tsx:9:75)
    at ./component/neraca/chart_data.tsx (D:\Projek\dashboard\.next\server\pages\index.js:88:1)
    at __webpack_require__ (D:\Projek\dashboard\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./component/neraca/index.tsx:17:69)
    at ./component/neraca/index.tsx (D:\Projek\dashboard\.next\server\pages\index.js:99:1)
    at __webpack_require__ (D:\Projek\dashboard\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:8:75)
    at ./pages/index.tsx (D:\Projek\dashboard\.next\server\pages\index.js:308:1)
    at __webpack_require__ (D:\Projek\dashboard\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (D:\Projek\dashboard\.next\server\pages\index.js:724:39)
    at D:\Projek\dashboard\.next\server\pages\index.js:725:28
    at Object.<anonymous> (D:\Projek\dashboard\.next\server\pages\index.js:728:3)
    at Object.requirePage (D:\Projek\dashboard\node_modules\next\dist\server\require.js:58:12)
    at D:\Projek\dashboard\node_modules\next\dist\server\load-components.js:61:73
    at async Object.loadComponents (D:\Projek\dashboard\node_modules\next\dist\server\load-components.js:61:26)
    at async DevServer.findPageComponents (D:\Projek\dashboard\node_modules\next\dist\server\next-server.js:555:36)
    at async DevServer.renderPageComponent (D:\Projek\dashboard\node_modules\next\dist\server\base-server.js:909:24)        
    at async DevServer.renderToResponse (D:\Projek\dashboard\node_modules\next\dist\server\base-server.js:938:32)
    at async DevServer.pipe (D:\Projek\dashboard\node_modules\next\dist\server\base-server.js:387:25)
    at async Object.fn (D:\Projek\dashboard\node_modules\next\dist\server\next-server.js:749:21)
    at async Router.execute (D:\Projek\dashboard\node_modules\next\dist\server\router.js:252:36)
    at async DevServer.run (D:\Projek\dashboard\node_modules\next\dist\server\base-server.js:365:29)
    at async DevServer.run (D:\Projek\dashboard\node_modules\next\dist\server\dev\next-dev-server.js:709:20)
    at async DevServer.handleRequest (D:\Projek\dashboard\node_modules\next\dist\server\base-server.js:303:20) {
  code: 'ERR_REQUIRE_ESM',
  page: '/'
}

**Comment by MMrj9** [comment]
Also getting this error in meteorjs

**Comment by guilhermewm** [comment]
@MMrj9 and @aseph8083 if you are using NextJS I believe you will need to lazy import on the client side as I did because the lib doesn't support ssr:

`const Column = dynamic(() => import('@ant-design/charts').then(({ Column }) => Column), { ssr: false })`

**Comment by aseph8083** [comment]
> @MMrj9 and @aseph8083 if you are using NextJS I believe you will need to lazy import on the client side as I did because the lib doesn't support ssr:
> 
> `const Column = dynamic(() => import('@ant-design/charts').then(({ Column }) => Column), { ssr: false })`

Thank you, this work for me
