### ISSUE TITLE
Can't use Antd chart in nextjs

### ISSUE THREAD

**Issue by ExorTek** [ant-design/ant-design-charts#1771]
- antd -> 4.22.4
- next -> 12.2.4
- react-dom -> 18.2.0
- react -> 18.2.0
- @ant-design/charts -> 1.4.2

> error - Error [ERR_REQUIRE_ESM]: require() of ES Module <myPath>/node_modules/d3-interpolate/src/index.js from <myPath>/node_modules/@antv/g-base/lib/animate/timeline.js not supported. Instead change the require of index.js in <myPath>/node_modules/@antv/g-base/lib/animate/timeline.js to a dynamic import() which is available in all CommonJS modules. at Object.<anonymous> (<myPath>/node_modules/@antv/g-base/lib/animate/timeline.js:5:24) at Object.<anonymous> (<myPath>/node_modules/@antv/g-base/lib/abstract/canvas.js:7:18) at Object.<anonymous> (<myPath>/node_modules/@antv/g-base/lib/index.js:17:16) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/dependents.js:6:16) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/util/scale.js:7:20) at Object.<anonymous> (/<myPath>/node_modules/@antv/g2/lib/util/axis.js:6:15) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/facet/facet.js:7:14) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/facet/index.js:5:15) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/chart/view.js:8:15) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/chart/chart.js:8:38) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/chart/index.js:7:15) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/core.js:10:15) at Object.<anonymous> (<myPath>/node_modules/@antv/g2/lib/index.js:6:14) at Object.<anonymous> (<myPath>/node_modules/@antv/g2plot/lib/index.js:7:31) at Object.<anonymous>(<myPath>/node_modules/@antdesign/plots/lib/components/area/index.js:41:16) at Object.<anonymous> (<myPath>/node_modules/@ant-design/plots/lib/index.js:21:30) at Object.<anonymous> (/<myPath>/node_modules/@ant-design/charts/lib/index.js:18:14) at @ant-design/charts (<myPath>/.next/server/pages/status.js:32:18) { code: 'ERR_REQUIRE_ESM', page: '/status' }

**Comment by ExorTek** [comment]
if you come for this problem i found the solution.

```js
import dynamic from "next/dynamic";

const Gauge = dynamic(() => import('@ant-design/charts').then((mod) => mod.Gauge), { ssr: false });
```
