### ISSUE TITLE
🧐[问题] 流程图引入直接报错了

### ISSUE THREAD

**Issue by junniao** [ant-design/ant-design-charts#2136]
### 🧐 根据官网示例引入 import { Flowchart } from '@ant-design/flowchart' 流程图
直接报错了。

### 💻 示例代码  报错了
Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'observers')
TypeError: Cannot read properties of null (reading 'observers')
    at RxModel.watch (http://localhost:3000/static/js/vendors-node_modules_ant-design_flowchart_es_graph_index_js-node_modules_form-render_es_widge-a0889c.chunk.js:86485:26)
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_flowchart_es_graph_index_js-node_modules_form-render_es_widge-a0889c.chunk.js:86349:31
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:143633:30)
    at invokePassiveEffectMountInDEV (http://localhost:3000/static/js/bundle.js:145322:17)
    at invokeEffectsInDev (http://localhost:3000/static/js/bundle.js:147221:15)
    at commitDoubleInvokeEffectsInDEV (http://localhost:3000/static/js/bundle.js:147204:11)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:146977:9)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:146915:18)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:146132:7)
    at flushSyncCallbacks (http://localhost:3000/static/js/bundle.js:134169:26)
ERROR

### 🚑 其他信息 
![Uploading 1696814265612.png…]()
"dependencies": {
"antd": "^5.5.2",
"@ant-design/charts": "^1.4.2",
  "@ant-design/icons": "^5.1.4",
"react-dom": "^18.2.0",
"lodash": "^4.17.21",

}
这是版本

**Comment by junniao** [comment]
引入玫瑰图柱状图全部报错，请问是什么问题呢
![Uploading image.png…]()
