### ISSUE TITLE
🐛[BUG] Mix chart with empty data failing unit tests

### ISSUE THREAD

**Issue by vgs18** [ant-design/ant-design-charts#2151]
### 🐛 bug description [Describe the bug in detail so that everyone can understand]
I am trying to write a unit test for a Mix chart, the tests pass without any issue with some data, whereas it fails with the following error for empty data.
There is no issue while rendering the same, but the issue is seen only for the unit tests. (Using jest and react testing library for unit testing).

TypeError: Cannot read properties of null (reading '1')

      at toRGB (node_modules/@antv/color-util/src/index.ts:93:35)
      at toRGB (node_modules/@antv/color-util/src/index.ts:109:48)
      at Object.func (node_modules/@antv/util/src/map.ts:12:17)
      at Object.map [as gradient] (node_modules/@antv/color-util/src/index.ts:108:18)
      at new gradient (node_modules/@antv/attr/src/attributes/color.ts:18:31)
      at _loop_1 (node_modules/@antv/g2/src/geometry/base.ts:1725:32)
      at Line.Geometry.initAttributes (node_modules/@antv/g2/lib/geometry/base.js:1195:21)
      at Line.initAttributes [as init] (node_modules/@antv/g2/src/geometry/base.ts:887:10)
      at View.init [as initGeometries] (node_modules/@antv/g2/src/chart/view.ts:1793:18)
      at View.initGeometries [as renderDataRecursive] (node_modules/@antv/g2/src/chart/view.ts:1539:10)
      at Chart.renderDataRecursive (node_modules/@antv/g2/src/chart/view.ts:1547:12)
      at Chart.renderDataRecursive [as paint] (node_modules/@antv/g2/src/chart/view.ts:1349:10)
      at Chart.paint [as render] (node_modules/@antv/g2/src/chart/view.ts:236:10)
      at Mix.render (node_modules/@antv/g2plot/src/core/plot.ts:164:16)
      at render (node_modules/@ant-design/plots/lib/hooks/useChart.js:147:23)
      at create (node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountOnFiber (node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at commitPassiveMountEffects (node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:26769:9)
      at callback (node_modules/react/cjs/react.development.js:2667:24)
      at flushActQueue (node_modules/react/cjs/react.development.js:2633:9)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2545:15)

### 📷 Reproduction steps [Clearly describe the reproduction steps so that others can see the problem]
Please use the below code to reproduce the issue and run the test provided
Tools used for testing -> jest, react testing library

### 🏞 Expected results [Describe the results you originally expected to see]
The test should pass without any issue.

### 💻 Replicate code [Provide reproducible code, warehouse, or online examples]
Following is the component code for rendering the chart and the unit test
**Component:**
import React from 'react';
import ReactDOM from 'react-dom';
import { Mix } from '@ant-design/plots';

const ColumnLine = () => {
  const data = [
    {
      month: 'Sep 23',
      cost: 200,
      type: 'Cost',
    },
    {
      month: 'Oct 23',
      cost: 300,
      type: 'Cost',
    },
  ];

 const config = {
    syncViewPadding: true,
    seriesField: 'type',
    plots: [
      {
        type: 'column',
        options: {
          data: data,
          xField: 'month',
          yField: 'cost',
        },
      },
      {
        type: 'line',
        options: {
          data: data,
          xField: 'month',
          yField: 'cost',
          xAxis: false,
          seriesField: 'type',
          animation: true,
          tooltip: false,
        },
      },
    ],
    tooltip: {
      shared: true,
    },
  };

  return <Mix {...config} />;
};

ReactDOM.render(<ColumnLine />, document.getElementById('container'));

**Unit tests:**
import { act, render } from '@testing-library/react';

import ColumnLine from '.';

it('should pass the test', async () => {
  await act(async () => render(<ColumnLine />));
});

### © Version information

- ant-design-charts version: [e.g. 0.9.0]
- Browser environment
- Development environment [e.g. mac OS]

### 🚑 Other information [Other information such as screenshots can be posted here]
<img width="1430" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/95902397/7a154055-24a2-4478-8f68-bb4a9ab3c3c9">

**Comment by vgs18** [comment]
Any updates on this?

**Comment by Shivansh-Purple** [comment]
I am also facing the same issue for unit tests

**Comment by vgs18** [comment]
Hi ant-design-charts team,
Waiting for some resolution here as this is a blocker for one of our products.
