### ISSUE TITLE
🐛[BUG] V2 - Time mask not working due to fetcha bug

### ISSUE THREAD

**Issue by MaxBarbet** [ant-design/ant-design-charts#2416]
### 🐛 bug description [describe the bug in detail so that everyone can understand it]

When using the time mask on xAxis in the V2 like this :
scale: {
            x: {
                type: 'time',
                min: "2023-01-01 00:00:00",
                max: "2024-01-01 00:00:00",
                mask: "MM/YYYY",
                tickMethod: () => labels
            }
        }

I have the "Invalid Date pass to format" in Chrome iOS with iso date format.

### 📷 Steps to Reproduce [clearly describe the steps to reproduce so others can see the problem too]

Create a component stackedColumnChart :

const StackedColumnChart = ({ labels, data }: { labels: string[], data: ChartValue[] }) => {
    const config = {
        data: data,
        isStack: true,
        appendPadding: 5,
        xField: 'label',
        yField: 'value',
        seriesField: 'name',
        legend: {
            position: "top" as const,
        },
        label: {
            layout: [
                {
                    type: 'interval-adjust-position',
                },
                {
                    type: 'interval-hide-overlap',
                },
                {
                    type: 'adjust-color',
                },
            ],
        },
        scale: {
            x: {
                type: 'time',
                min: "2023-01-01 00:00:00",
                max: "2024-01-01 00:00:00",
                mask: "MM/YYYY",
                tickMethod: () => labels
            }
        }
    };

    console.log(data)

    return (
            <Column {...config} />
    );
}

Send to the component data with labels on iso date format like :
"2023-01-01T00:00:00.000Z"

### 🏞 Desired Results [Describe the results you would have expected to see]
A working mask displaying time with a MM/YYYY appearance

### © Version Information

- ant-design-charts Version: [e.g. 2.0.0]
- Browser Environment : Chrome
- Development environment [e.g. mac OS].

### 🚑 Additional information [additional information such as screenshots can be posted here]

ERROR
Invalid Date pass to format
    at format (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:87251:11)
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:77637:62
    at Array.map (<anonymous>)
    at labelsOf (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:62079:16)
    at computeLabelsBBox (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:62018:18)
    at computeAxisSize (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:61801:23)
    at computeComponentSize (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:61730:25)
    at autoSizeOf (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:62588:73)
    at Array.forEach (<anonymous>)
    at computePadding (http://localhost:3000/static/js/vendors-node_modules_ant-design_plots_es_components_line_index_js.chunk.js:62614:17)

Uncaught (in promise) Error: Invalid Date pass to format
    at format (fecha.ts:312:1)
    at time.ts:53:1
    at Array.map (<anonymous>)
    at labelsOf (component.ts:1054:1)
    at computeLabelsBBox (component.ts:970:1)
    at computeAxisSize (component.ts:724:1)
    at computeComponentSize (component.ts:603:1)
    at autoSizeOf (layout.ts:332:1)
    at Array.forEach (<anonymous>)
    at computePadding (layout.ts:373:1)

**Comment by lxfu1** [comment]
V2 does not support mask configuration yet, please handle the data.
