### ISSUE TITLE
🐛[BUG]nextjs 14.0.4使用ant0design-charts 2.0.2 build error

### ISSUE THREAD

**Issue by Wizarddm** [ant-design/ant-design-charts#2425]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
ReferenceError: document is not defined
    at 35085 (/Users/xiaomin/code/zz-frontend/.next/server/app/dashboard/page.js:1:15501)
    at t (/Users/xiaomin/code/zz-frontend/.next/server/webpack-runtime.js:1:128)
    at F (/Users/xiaomin/code/zz-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at /Users/xiaomin/code/zz-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94352
    at W._fromJSON (/Users/xiaomin/code/zz-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94790)
    at JSON.parse (<anonymous>)
    at N (/Users/xiaomin/code/zz-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91658)
    at t (/Users/xiaomin/code/zz-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:98043)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
官方示例的圆环图
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1241" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/18689193/c651cdfa-cacb-4154-b52d-f64781b10507">

**Comment by lxfu1** [comment]
dynamic import? https://github.com/ant-design/ant-design-charts/issues/215

**Comment by kyujonglee** [comment]
same problem. :(

**Comment by SsspongeBob** [comment]
same problem

**Comment by conquera99** [comment]
update react dependencies to below version if still not work:

```
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
```
