### ISSUE TITLE
🐛[BUG]从版本1.4.3升级为2.0.3，桑基图无法使用。

### ISSUE THREAD

**Issue by jurendada** [ant-design/ant-design-charts#2432]
从版本1.4.3升级为2.0.3，桑基图无法使用。
回退至1.4.3版本能正确显示桑基图。
浏览器控制台：
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sourceLinks')
    at sankey.ts:175:14
    at Array.forEach (<anonymous>)
    at computeNodeLinks (sankey.ts:168:11)
    at sankey (sankey.ts:76:5)
    at sankey.ts:69:24
    at Sankey3 (sankey.ts:85:14)
    at use (library.ts:31:12)
    at plot.ts:597:29
    at Generator.next (<anonymous>)
    at fulfilled (mark.ts:184:1)

**Comment by lxfu1** [comment]
参考下V2的示例呢？ https://ant-design-charts-next.antgroup.com/examples/statistics/sankey/#alipay
