### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by JoeCMorgan** [ant-design/ant-design-charts#255]
I'm getting the following error when trying to run any tests in my project after installing Ant-designs-charts

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /.../frontend-toolkit/node_modules/@antv/g6/es/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { version } from '../package.json';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (../../node_modules/@ant-design/charts/lib/graph/organizationTreeGraph.js:12:34)
```

What do I need to set inside my jest/babel config to fix?

**Comment by lxfu1** [comment]
Reference https://medium.com/@fredriccliver/syntaxerror-cannot-use-import-statement-outside-a-module-69182014b8c6

**Comment by resurtm** [comment]
Hey @lxfu1,

It doesn't really work for me unfortunately.
Any other workaroud/fix?

Thanks!

**Comment by resurtm** [comment]
@JoeCMorgan, have you fixed it somehow? Thanks!

**Comment by lxfu1** [comment]
> Hey @lxfu1,
> 
> It doesn't really work for me unfortunately.
> Any other workaroud/fix?
> 
> Thanks!

https://github.com/webpack-contrib/json-loader
