### ISSUE TITLE
🐛[BUG] ReferenceError: document is not defined on Nextjs

### ISSUE THREAD

**Issue by sturlath** [ant-design/ant-design-charts#360]
Hi

This is probably not a bug but I can't get G2 to run on NextJs (server-side).

If I add the [example page](https://github.com/ant-design/ant-design-charts) to NextJs and just run it I get the following error.

> ReferenceError: document is not defined
    at Object.<anonymous> (C:\dev\node_modules\@antv\g2\lib\util\text.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\dev\node_modules\@antv\g2\lib\geometry\label\layout\limit-in-plot.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

Is there a way around this?

**Comment by sturlath** [comment]
I have been playing around with this and thought I had found a solution but I'm not getting it to work. Is [this a fix here](https://github.com/vercel/next.js/issues/7400#issuecomment-739318238) something that you think could work and if so could you give me some hints on applying it?

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/215

**Comment by sturlath** [comment]
Awesome! Thank you @lxfu1. I'll close this now.
