### ISSUE TITLE
 🐛[BUG] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Necmttn** [ant-design/ant-design-charts#395]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
~/node_modules/@antv/g6/es/index.js:1
import { version } from '../package.json';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (~/node_modules/@ant-design/charts/lib/graph/organizationTreeGraph.js:26:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Necmttn** [comment]
Refer to https://github.com/ant-design/ant-design-charts/issues/215#issuecomment-701149276

**Comment by jernkuan** [comment]
It's unfortunate we would need to do this workaround, can someone explain the actual issue and the cause?

I'm facing similar issues but the workaround work.

    at Object.<anonymous> (/xxxxx/node_modules/@antv/algorithm/lib/workers/index.js:8:44)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/xxxxx/node_modules/@antv/algorithm/lib/index.js:252:14)

It should have loaded the xxxxx/algorithm/es/index.js instead?
