### ISSUE TITLE
Support to React 17x + jest

### ISSUE THREAD

**Issue by naminder** [ant-design/ant-design-charts#518]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]:
It should work with react 17x + typescript

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
On using gettinge below error in jest:
node_modules/lodash-es/isTypedArray.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import baseIsTypedArray from './_baseIsTypedArray.js';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@antv/g-webgpu-core/src/components/geometry/GeometryComponent.ts:2:1)

**Comment by lxfu1** [comment]
I tested with React17 and work well, can you provide your code?

**Comment by lxfu1** [comment]
https://github.com/lxfu1/my-app-react17

**Comment by naminder** [comment]
Hi @lxfu1 ,

I no longer have the code as I went for high charts.

I was using "Liquid" and "Pie" component, a simple functional component render with all the required data as advised in documentation. The application worked fine but the jest test cases failed with this error.

My versions were:
"@ant-design/charts": "1.0.18",
"antd": "4.9.4",
"react": "^17.0.1",
"react-dom": "^17.0.1",
"typescript": "4.1.2"

`TypeError: Cannot read property 'save' of null

      at Object.getTextWidth (node_modules/@antv/g-base/src/util/text.ts:44:11)
      at default_1 (node_modules/@antv/g-base/src/bbox/text.ts:13:17)
      at Text.ShapeBase.calculateBBox (node_modules/@antv/g-canvas/src/shape/base.ts:44:17)
      at Text.AbstractShape.getBBox (node_modules/@antv/g-base/src/abstract/shape.ts:29:19)
      at Text.AbstractShape.calculateCanvasBBox (node_modules/@antv/g-base/src/abstract/shape.ts:61:23)
      at Text.AbstractShape.getCanvasBBox (node_modules/@antv/g-base/src/abstract/shape.ts:38:25)
      at node_modules/@antv/g-base/src/abstract/container.ts:130:27
      at Object.each (node_modules/@antv/util/src/each.ts:11:13)
      at Group.Container.getCanvasBBox (node_modules/@antv/g-base/src/abstract/container.ts:129:7)
      at node_modules/@antv/g2/src/geometry/label/layout/limit-in-plot.ts:47:67
      at Object.each (node_modules/@antv/util/src/each.ts:11:13)
      at limitInPlot (node_modules/@antv/g2/src/geometry/label/layout/limit-in-plot.ts:46:3)
      at node_modules/@antv/g2/src/component/labels.ts:218:11
      at Object.each (node_modules/@antv/util/src/each.ts:11:13)
      at Labels.doLayout (node_modules/@antv/g2/src/component/labels.ts:208:7)
      at Labels.render (node_modules/@antv/g2/src/component/labels.ts:63:12)
      at IntervalLabel.GeometryLabel.render (node_modules/@antv/g2/src/geometry/label/base.ts:82:20)
      at Interval.Geometry.renderLabels (node_modules/@antv/g2/src/geometry/base.ts:2000:19)
      at Interval.Geometry.paint (node_modules/@antv/g2/src/geometry/base.ts:960:12)
      at Chart.View.paintGeometries (node_modules/@antv/g2/src/chart/view.ts:1891:16)
      at Chart.View.renderPaintRecursive (node_modules/@antv/g2/src/chart/view.ts:1413:10)
      at Chart.View.paint (node_modules/@antv/g2/src/chart/view.ts:1286:10)
      at Chart.View.render (node_modules/@antv/g2/src/chart/view.ts:230:10)
      at Bullet.render (node_modules/@antv/g2plot/src/core/plot.ts:161:16)
      at create (node_modules/@ant-design/charts/lib/hooks/useChart.js:147:23)
      at apply (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.apply (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at eventHandler (node_modules/react-dom/cjs/react-dom.development.js:23574:9)
      at Scheduler_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:646:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:23447:14)
      at flushWork (node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
      at flushWorkAndMicroTasks (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1001:5)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1080:11`

On degrading the application to 16.13 it worked fine.

Thanks for looking into it.

**Comment by lxfu1** [comment]
I have tested Pie and Liquid and they both work well. Please provide the duplicate code next time you have a problem. Thanks.

**Comment by lxfu1** [comment]
jest-setup.js  `jest-canvas-mock`
```ts
import "@testing-library/jest-dom";
import "jest-canvas-mock";
import "whatwg-fetch";

class Worker {
  url;
  onmessage;
  constructor(stringUrl) {
    this.url = stringUrl;
    this.onmessage = () => {};
  }

  postMessage(msg) {
    this.onmessage(msg);
  }
}

Object.defineProperty(URL, "createObjectURL", {
  writable: true,
  value: jest.fn(),
});

window.Worker = Worker;

```
